#!/bin/bash

. colors

VERS="0.1.0.pi"

get_cpu_temp () {
vcgencmd measure_temp | cut -d "=" -f 2 | cut -d "'" -f 1
}

print_help(){
    echo -e "${CYAN}Hive cpu-temp Helper v$VERS"
    echo -e "${WHITE}This tool shows CPU temp."
    echo
    echo -e "${YELLOW}Usage:"
    echo -e "\t${CYAN}cpu-temp      ${LGRAY}- current CPU temp value"
    echo
    echo -e "${YELLOW}Other examples of usage:${NOCOLOR}"
    echo -e "\t${CYAN}cpu-temp -h   ${LGRAY}- print this help ${NOCOLOR}"
}

################################################################################
# MAIN SCRIPT BODY
################################################################################

case $1 in
    -h|--help)
        print_help
        exit 0
        ;;
    *)
        get_cpu_temp
        ;;
esac
